"""create_all_tables

Revision ID: 0c28d12a7ccf
Revises: 
Create Date: 2026-04-23 16:11:52.405430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c28d12a7ccf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index(op.f('ix_department_department_id'), 'department', ['department_id'], unique=False)
    op.create_table('level',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_index(op.f('ix_level_level_id'), 'level', ['level_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_table('semesters',
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('semester_name', sa.String(length=100), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('semester_id')
    )
    op.create_index(op.f('ix_semesters_semester_id'), 'semesters', ['semester_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('university_name', sa.String(length=150), nullable=False),
    sa.Column('college_name', sa.String(length=150), nullable=False),
    sa.Column('right_logo_path', sa.String(length=500), nullable=True),
    sa.Column('left_logo_path', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('setting_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('activity_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('table_affected', sa.String(length=50), nullable=True),
    sa.Column('action_details', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_activity_log_log_id'), 'activity_log', ['log_id'], unique=False)
    op.create_index(op.f('ix_activity_log_timestamp'), 'activity_log', ['timestamp'], unique=False)
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_admin_admin_id'), 'admin', ['admin_id'], unique=False)
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.level_id'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_name', 'level_id', name='UQ_Course_Level')
    )
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_id'], unique=False)
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.level_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('university_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_student_student_id'), 'student', ['student_id'], unique=False)
    op.create_table('teacher',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teacher_teacher_id'), 'teacher', ['teacher_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('verification_codes',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_index(op.f('ix_verification_codes_code_id'), 'verification_codes', ['code_id'], unique=False)
    op.create_index(op.f('ix_verification_codes_user_id'), 'verification_codes', ['user_id'], unique=False)
    op.create_table('backup_history',
    sa.Column('backup_id', sa.Integer(), nullable=False),
    sa.Column('backup_type', sa.String(length=50), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('backup_date', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('backup_id')
    )
    op.create_index(op.f('ix_backup_history_backup_id'), 'backup_history', ['backup_id'], unique=False)
    op.create_table('course_departments',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'department_id')
    )
    op.create_table('import_history',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.PrimaryKeyConstraint('import_id')
    )
    op.create_index(op.f('ix_import_history_import_id'), 'import_history', ['import_id'], unique=False)
    op.create_table('student_courses',
    sa.Column('sc_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sc_id'),
    sa.UniqueConstraint('student_id', 'course_id', 'semester_id', name='UQ_Student_Course_Semester')
    )
    op.create_index(op.f('ix_student_courses_sc_id'), 'student_courses', ['sc_id'], unique=False)
    op.create_index(op.f('ix_student_courses_student_id'), 'student_courses', ['student_id'], unique=False)
    op.create_table('teacher_courses',
    sa.Column('tc_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tc_id'),
    sa.UniqueConstraint('teacher_id', 'course_id', 'department_id', 'semester_id', name='UQ_Teacher_Course_Dept_Semester')
    )
    op.create_index(op.f('ix_teacher_courses_tc_id'), 'teacher_courses', ['tc_id'], unique=False)
    op.create_index(op.f('ix_teacher_courses_teacher_id'), 'teacher_courses', ['teacher_id'], unique=False)
    op.create_table('folder',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('folder_name', sa.String(length=100), nullable=False),
    sa.Column('tc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tc_id'], ['teacher_courses.tc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_id')
    )
    op.create_index(op.f('ix_folder_folder_id'), 'folder', ['folder_id'], unique=False)
    op.create_table('exam',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('exam_title', sa.String(length=150), nullable=False),
    sa.Column('number_of_questions', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('passing_mark', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('allowed_time', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.folder_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_index(op.f('ix_exam_exam_id'), 'exam', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_folder_id'), 'exam', ['folder_id'], unique=False)
    op.create_table('answer_sheet',
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_earned_mark', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('total_earned_mark >= 0', name='CHK_TotalEarnedMark'),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.exam_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sheet_id'),
    sa.UniqueConstraint('student_id', 'exam_id', name='UQ_Student_Exam')
    )
    op.create_index(op.f('ix_answer_sheet_sheet_id'), 'answer_sheet', ['sheet_id'], unique=False)
    op.create_index(op.f('ix_answer_sheet_student_id'), 'answer_sheet', ['student_id'], unique=False)
    op.create_table('exam_departments',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.exam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id', 'department_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_mark', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('reference_image', sa.String(length=500), nullable=True),
    sa.CheckConstraint('question_mark >= 0', name='CHK_QuestionMark'),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.exam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=False)
    op.create_table('expected_answers',
    sa.Column('expected_answer_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expected_answer_id')
    )
    op.create_index(op.f('ix_expected_answers_expected_answer_id'), 'expected_answers', ['expected_answer_id'], unique=False)
    op.create_table('report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.String(), nullable=True),
    sa.Column('areas_of_improvement', sa.String(), nullable=True),
    sa.Column('academic_description', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sheet_id'], ['answer_sheet.sheet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('sheet_id')
    )
    op.create_index(op.f('ix_report_report_id'), 'report', ['report_id'], unique=False)
    op.create_table('sheet_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['answer_sheet.sheet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_sheet_images_image_id'), 'sheet_images', ['image_id'], unique=False)
    op.create_index(op.f('ix_sheet_images_sheet_id'), 'sheet_images', ['sheet_id'], unique=False)
    op.create_table('student_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.String(), nullable=True),
    sa.Column('ai_mark', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('teacher_mark', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_feedback', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['answer_sheet.sheet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index(op.f('ix_student_answers_answer_id'), 'student_answers', ['answer_id'], unique=False)
    op.create_index(op.f('ix_student_answers_sheet_id'), 'student_answers', ['sheet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_answers_sheet_id'), table_name='student_answers')
    op.drop_index(op.f('ix_student_answers_answer_id'), table_name='student_answers')
    op.drop_table('student_answers')
    op.drop_index(op.f('ix_sheet_images_sheet_id'), table_name='sheet_images')
    op.drop_index(op.f('ix_sheet_images_image_id'), table_name='sheet_images')
    op.drop_table('sheet_images')
    op.drop_index(op.f('ix_report_report_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_expected_answers_expected_answer_id'), table_name='expected_answers')
    op.drop_table('expected_answers')
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('exam_departments')
    op.drop_index(op.f('ix_answer_sheet_student_id'), table_name='answer_sheet')
    op.drop_index(op.f('ix_answer_sheet_sheet_id'), table_name='answer_sheet')
    op.drop_table('answer_sheet')
    op.drop_index(op.f('ix_exam_folder_id'), table_name='exam')
    op.drop_index(op.f('ix_exam_exam_id'), table_name='exam')
    op.drop_table('exam')
    op.drop_index(op.f('ix_folder_folder_id'), table_name='folder')
    op.drop_table('folder')
    op.drop_index(op.f('ix_teacher_courses_teacher_id'), table_name='teacher_courses')
    op.drop_index(op.f('ix_teacher_courses_tc_id'), table_name='teacher_courses')
    op.drop_table('teacher_courses')
    op.drop_index(op.f('ix_student_courses_student_id'), table_name='student_courses')
    op.drop_index(op.f('ix_student_courses_sc_id'), table_name='student_courses')
    op.drop_table('student_courses')
    op.drop_index(op.f('ix_import_history_import_id'), table_name='import_history')
    op.drop_table('import_history')
    op.drop_table('course_departments')
    op.drop_index(op.f('ix_backup_history_backup_id'), table_name='backup_history')
    op.drop_table('backup_history')
    op.drop_index(op.f('ix_verification_codes_user_id'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_code_id'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_teacher_teacher_id'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_student_student_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_courses_course_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_admin_admin_id'), table_name='admin')
    op.drop_table('admin')
    op.drop_index(op.f('ix_activity_log_timestamp'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_log_id'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_semesters_semester_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_level_level_id'), table_name='level')
    op.drop_table('level')
    op.drop_index(op.f('ix_department_department_id'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
