"""Add is_published to AnswerSheet

Revision ID: afd1b5ed907f
Revises: 0c28d12a7ccf
Create Date: 2026-06-18 04:42:53.364664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afd1b5ed907f'
down_revision: Union[str, Sequence[str], None] = '0c28d12a7ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('UQ_Student_Exam', 'answer_sheet', ['student_id', 'exam_id'])
    op.alter_column('exam', 'exam_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.drop_constraint(op.f('exam_departments_department_id_fkey'), 'exam_departments', type_='foreignkey')
    op.create_foreign_key(None, 'exam_departments', 'department', ['department_id'], ['department_id'])
    op.alter_column('expected_answers', 'match_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('question_groups', 'exam_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question_groups', 'group_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('question_groups', 'group_total_mark',
               existing_type=sa.REAL(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.create_index(op.f('ix_question_groups_group_id'), 'question_groups', ['group_id'], unique=False)
    op.drop_constraint(op.f('question_groups_exam_id_fkey'), 'question_groups', type_='foreignkey')
    op.create_foreign_key(None, 'question_groups', 'exam', ['exam_id'], ['exam_id'], ondelete='CASCADE')
    op.alter_column('question_sections', 'section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('question_sections', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question_sections', 'section_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('question_sections', 'section_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_question_sections_section_id'), 'question_sections', ['section_id'], unique=False)
    op.drop_constraint(op.f('question_sections_group_id_fkey'), 'question_sections', type_='foreignkey')
    op.create_foreign_key(None, 'question_sections', 'question_groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.alter_column('questions', 'exam_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('questions', 'question_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'question_mark',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('questions', 'question_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('questions_section_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'question_sections', ['section_id'], ['section_id'], ondelete='CASCADE')
    op.drop_column('questions', 'reference_image')
    op.alter_column('student_courses', 'subject_strengths',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('student_courses', 'subject_weaknesses',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('student_courses', 'last_ai_update',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('verification_codes', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_codes', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('student_courses', 'last_ai_update',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('student_courses', 'subject_weaknesses',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('student_courses', 'subject_strengths',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('questions', sa.Column('reference_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_section_id_fkey'), 'questions', 'question_sections', ['section_id'], ['section_id'], onupdate='CASCADE')
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('questions', 'question_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'question_mark',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('questions', 'question_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('questions', 'exam_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'question_sections', type_='foreignkey')
    op.create_foreign_key(op.f('question_sections_group_id_fkey'), 'question_sections', 'question_groups', ['group_id'], ['group_id'], onupdate='CASCADE')
    op.drop_index(op.f('ix_question_sections_section_id'), table_name='question_sections')
    op.alter_column('question_sections', 'section_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('question_sections', 'section_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('question_sections', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question_sections', 'section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'question_groups', type_='foreignkey')
    op.create_foreign_key(op.f('question_groups_exam_id_fkey'), 'question_groups', 'exam', ['exam_id'], ['exam_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_question_groups_group_id'), table_name='question_groups')
    op.alter_column('question_groups', 'group_total_mark',
               existing_type=sa.Numeric(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('question_groups', 'group_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('question_groups', 'exam_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('expected_answers', 'match_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'exam_departments', type_='foreignkey')
    op.create_foreign_key(op.f('exam_departments_department_id_fkey'), 'exam_departments', 'department', ['department_id'], ['department_id'], ondelete='CASCADE')
    op.alter_column('exam', 'exam_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint('UQ_Student_Exam', 'answer_sheet', type_='unique')
    # ### end Alembic commands ###
